quranChapter=[
    {
        id:1,
        name:"سورة الفاتحة",
        summery:" سورة مكية ، آياتها 7"
    },
    {
        id:2,
        name:"سورة البقرة",
        summery:"سورة مدنية ، آياتها 286"
    },
    {
        id:3,
        name:"سورة آل عمران",
        summery:"سورة مدنية ، آياتها 200 " 
    }
	,
    {
        id:4,
        name:"النساء",
        summery:"سورة مدنية ، آياتها 176" 
    }
	,
    {
        id:5,
        name:"سورة المائدة",
        summery:"سورة مدنية ، آياتها 120" 
    },
    {
        id:6,
        name:" سورة الأنعام",
        summery:" سورة مكية ، آياتها 165" 
    },
    {
        id:7,
        name:"سورة الأعراف",
        summery:"سورة مكية ، آياتها 206" 
    },
    {
        id:8,
        name:"سورة الأنفال",
        summery:"سورة مدنية ، آياتها 75" 
    },
    {
        id:9,
        name:"سورة التوبة",
        summery:"سورة مدنية ، آياتها 129" 
    },
    {
        id:10,
        name:"سورة يونس",
        summery:"سورة مكية ، آياتها 109" 
    },
    {
        id:11,
        name:"سورة هود",
        summery:"سورة مكية ، آياتها 123\n قال صلى الله عليه وسلم : ( شيبتني هود و أخواتها من المفصل ) [ صحيح الجامع الصغير/3722 ]" 
    },
    {
        id:12,
        name:" سورة يوسف",
        summery:"سورة مكية ، آياتها 111" 
    }/*,
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    },
    {
        id:,
        name:"",
        summery:"" 
    }*/
    ]
quranQare2=[
   
    {
        id:"1",
        link:"http://server11.mp3quran.net/shatri/",
        name:" أبو بكر الشاطري"
    },
	{
        id:"2",
        link:"http://server10.mp3quran.net/ajm/",
        name:" أحمد بن علي العجمي"
    },
	{
        id:"3",
        link:"http://server5.mp3quran.net/ahmad_nu/",
        name:" أحمد نعينع"
    },
	{
        id:"4",
        link:"http://server10.mp3quran.net/qht/",
        name:"خالد القحطاني"
    },
	{
        id:"5",
        link:"http://server5.mp3quran.net/kafi/",
        name:"خالد عبدالكافي"
    },
	{
        id:"6",
        link:"http://server7.mp3quran.net/s_gmd/",
        name:"سعد الغامدي"
    },
	{
        id:"7",
        link:"http://server7.mp3quran.net/shur/",
        name:"سعود الشريم "
    },
	{
        id:"8",
        link:"http://server8.mp3quran.net/bu_khtr/",
        name:"صلاح بو خاطر"
    },
	{
        id:"9",
        link:"http://server7.mp3quran.net/basit/",
        name:"عبدالباسط عبدالصمد"
    },
	{
        id:"10",
        link:"http://server11.mp3quran.net/sds/",
        name:"عبدالرحمن السديس"
    },
	{
        id:"12",
        link:"http://server9.mp3quran.net/hthfi/",
        name:"علي بن عبدالرحمن الحذيفي"
    },
	{
        id:"13",
        link:"http://server5.mp3quran.net/maher/",
        name:"ماهر المعيقلي"
    },
	{
        id:"11",
        link:"http://server5.mp3quran.net/kyat/",
        name:" عبدالله خياط "
    },
	{
        id:"14",
        link:"http://server5.mp3quran.net/tblawi/",
        name:"محمد الطبلاوي"
    },
	{
        id:"15",
        link:"http://server5.mp3quran.net/minsh/",
        name:"محمد صديق المنشاوي"
    },
	{
        id:"16",
        link:"http://server8.mp3quran.net/jbrl/",
        name:"محمد جبريل"
    },
	{
        id:"17",
        link:"http://server9.mp3quran.net/husr/",
        name:"محمود خليل الحصري "
    },	
	{
        id:"18",
        link:"http://server8.mp3quran.net/afs/",
        name:"مشاري العفاسي"
    },	
	{
        id:"19",
        link:"http://server8.mp3quran.net/mustafa/",
        name:" مصطفى إسماعيل"
    }
	
]